SELECT T.*, CAST(SNAPSHOTTIME AS DATE),CAST(SNAPSHOTTIME AS Time(0)),CAST(SNAPSHOTTIME AS CHAR(19))
FROM [stock] T
WHERE CAST(SNAPSHOTTIME AS CHAR(19)) = '2019-07-12 09:10:01'
ORDER BY SnapShotTime DESC